# Generated by Django 3.2.9 on 2021-11-27 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_header_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='add_image',
        ),
    ]
