# Generated by Django 3.2.9 on 2021-11-27 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_header_image_post_add_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='add_image',
            new_name='header_image',
        ),
    ]
