networks:
  my_site:
    driver: bridge
    name: django-docker-network

services:
  db:
    restart: always
    image: postgres:13
    container_name: db
    networks:
      - my_site
    ports:
      - 5432:5432
    env_file:
      - ./conf/postgres.env
  api:
    image: daniil030791/new_repo:1
    networks:
      - my_site
    volumes:
      - static_volume:/opt/api_blog/staticfiles
    ports:
      - 9000:9000
    env_file:
      - ./conf/django_api.env
    depends_on:
      - db
    links:
      - db:db

  ui:
    image: daniil030791/new_repo:2
    networks:
      - my_site
    ports:
      - 9001:9001
    depends_on:
      - api
  nginx:
    image: nginx:1.13
    networks:
      - my_site
    ports:
      - 80:80
    depends_on:
      - api
      - ui
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/opt/api_blog/staticfiles
volumes:
  static_volume:
