# Generated by Django 3.2.9 on 2021-12-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211203_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('coding', 'coding'), ('entertainment', 'entertainment'), ('other', 'other'), ('new', 'new')], default='new', max_length=100),
        ),
    ]
